// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdIWRgAHyOjlw5WmnQcUCeDczHWJblCiE',
    appId: '1:836584555388:web:ecc48fe15cb25c85015af9',
    messagingSenderId: '836584555388',
    projectId: 'club-app-d7084',
    authDomain: 'club-app-d7084.firebaseapp.com',
    databaseURL: 'https://club-app-d7084-default-rtdb.firebaseio.com',
    storageBucket: 'club-app-d7084.firebasestorage.app',
    measurementId: 'G-4X4KVBM4EP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVk_wg-kj12Ejde5aMt9kY01aHtu4rfjU',
    appId: '1:836584555388:android:9624a6ab45718fac015af9',
    messagingSenderId: '836584555388',
    projectId: 'club-app-d7084',
    databaseURL: 'https://club-app-d7084-default-rtdb.firebaseio.com',
    storageBucket: 'club-app-d7084.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAACZhVK_G6VLlvqTz3f2_59mcHWbWSpPQ',
    appId: '1:836584555388:ios:01faa65a79efa6b9015af9',
    messagingSenderId: '836584555388',
    projectId: 'club-app-d7084',
    databaseURL: 'https://club-app-d7084-default-rtdb.firebaseio.com',
    storageBucket: 'club-app-d7084.firebasestorage.app',
    iosBundleId: 'com.example.club',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAACZhVK_G6VLlvqTz3f2_59mcHWbWSpPQ',
    appId: '1:836584555388:ios:01faa65a79efa6b9015af9',
    messagingSenderId: '836584555388',
    projectId: 'club-app-d7084',
    databaseURL: 'https://club-app-d7084-default-rtdb.firebaseio.com',
    storageBucket: 'club-app-d7084.firebasestorage.app',
    iosBundleId: 'com.example.club',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCdIWRgAHyOjlw5WmnQcUCeDczHWJblCiE',
    appId: '1:836584555388:web:cc5bb086410e74cb015af9',
    messagingSenderId: '836584555388',
    projectId: 'club-app-d7084',
    authDomain: 'club-app-d7084.firebaseapp.com',
    databaseURL: 'https://club-app-d7084-default-rtdb.firebaseio.com',
    storageBucket: 'club-app-d7084.firebasestorage.app',
    measurementId: 'G-TVNG3WW5QY',
  );

}